config/routes.rb
Rails.application.routes.draw do
  root to: 'schedules#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  def validate_end_dates_cannot_be_in_the_past
    if enddate.present? && enddate < startdate
      errors.add(:enddate,"は開始日より前の日付は設定できません")
    end
  end

  validates :title, presence: true, length: { maximum:20 }
  validates :startdate, presence: true
  validates :enddate, presence: true 
  validate :validate_end_dates_cannot_be_in_the_past
  validates :memo, length: { maximum:500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :startdate, :enddate, :allday, :memo))
    if @schedule.save
      flash[:notice] = "予定を新規登録しました"
      redirect_to :schedules
    else
      render "new"
  end
end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :startdate, :enddate, :allday, :memo))
      flash[:notice] = "IDが「#{@schedule.id}」の予定を更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :schedules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduleapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/edit.html.erb
<%= render "shared/apptitle" %>

<h3 class="bg-info-subtle text-center">予定の編集</h3>

<%= render "shared/error", object: @schedule %> <%# ここを追記してみた %>

<%= form_with model: @schedule do |f| %>
  <div class="background-area">
    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :title, "タイトル" %></div>
      <div><%= f.text_field :title %></div> 
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :startdate, "開始日" %></div>
      <div><%= f.date_select :startdate %></div>
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :enddate, "終了日" %></div>
      <div><%= f.date_select :enddate %></div>
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :allday, "終日" %></div>
      <div><%= f.check_box :allday  %></div>
      <div>終日の場合はチェックを入れる</div>
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :memo, "スケジュールメモ" %></div>
      <div><%= f.text_area :memo %></td>
    </div>
  </div>

  <div>
    <ul>
      <li><%= f.submit "編集を確定する" %></li>
      <li><%= link_to "予定一覧に戻る", :schedules %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/index.html.erb
<div class="bg-body-secondary">

  <%= render "shared/apptitle" %>

  <h3 class="bg-info-subtle text-center">予定一覧</h3>

  <div class="link_to_button">
    <p><%= link_to "予定を新規登録する", :new_schedule, class:"btn btn-primary" %></p>
  </div>


  <% if flash[:notice] %>
    <p class="notice bg-warning"><%= flash[:notice] %></p>
  <% end %>

  
  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日</th>
        <th>更新日時</th>
        <th>詳細</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>

    <tbody>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.id %></td>
          <td><%= schedule.title %></td>
          <td><%= l schedule.startdate %></td>
          <td><%= l schedule.enddate %></td>
          <td><%= schedule.allday ? '○' : '' %></td>
          <td><%= l schedule.updated_at %></td>
          <td>
            <%= link_to "詳細", schedule %>
          </td>
          <td>
            <%= link_to "編集", [:edit, schedule] %>
          </td>
          <td>
            <%= link_to "削除", schedule, method: :delete, data: { confirm: '予定を削除しますか?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-between">
    <div>登録されている予定<%= Schedule.count %>件</div>
    <div>本日の日付 <%= l Date.today %> </div>
  </div>
</div>

app/views/schedules/new.html.erb
<%= render "shared/apptitle" %>

<h3 class="bg-info-subtle text-center">予定の新規登録</h3>

<%= render "shared/error", object: @schedule %>

<%= form_with model: @schedule do |f| %>
  <div>
    <div>
      <div class="my-2 bg-dark-subtle" ><%= f.label :title, "タイトル" %></div>
      <div><%= f.text_field :title %></div> 
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :startdate, "開始日" %></div>
      <div><%= f.date_select :startdate %></div>
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :enddate, "終了日" %></div>
      <div><%= f.date_select :enddate %></div>
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :allday, "終日" %></div>
      <div><%= f.check_box :allday %>終日の場合はチェックを入れる</div>
    </div>

    <div>
      <div class="my-2 bg-dark-subtle"><%= f.label :memo, "スケジュールメモ" %></div>
      <div><%= f.text_area :memo %></td>
    </div>
  </div>

  <div>
    <ul>
      <li><%= f.submit "予定を登録する" %></li>
      <li><%= link_to "予定一覧に戻る", :schedules %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/show.html.erb
<%= render "shared/apptitle" %>

<h3 class="bg-info-subtle text-center">予定の詳細</h3>

<div class="container">
  <div class="row">
    <div class="column">
      <div class="bg-dark-subtle">タイトル</div>
      <div class="bg-body-secondary"><%= @schedule.title %></div>
    </div>
    <div class="column">
    <div class="bg-dark-subtle">開始日</div>
    <div class="bg-body-secondary"><%= l @schedule.startdate %></div>
  </div>
  <div>
    <div class="bg-dark-subtle">終了日</div>
    <div class="bg-body-secondary"><%= l @schedule.enddate %></div>
  </div>
  <div>
    <div class="bg-dark-subtle">終日</div>
    <div class="bg-body-secondary"><%= @schedule.allday ? '○' : '' %></div>
  </div>
  <div>
    <div class="bg-dark-subtle">スケジュールメモ</div>
    <div class="bg-body-secondary"><%= @schedule.memo %></div>
    </div>
  </div>
</div>

<div>
  <ul>
    <li><%= button_to "この予定を編集する", edit_schedule_path, method: :get %></li>
    <li><%= link_to "予定一覧に戻る", :schedules %></li>
  </ul>
</div>

app/views/shared/_apptitle.html.erb
<h2 class="m-0 bg-info text-center">スケジュール管理アプリ</h2>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>